REPLICATION_KEYS = ["lastmodifieddate", "lastmoddate"]

SEARCH_ONLY_FIELDS = ["AccountingTransaction", "Item", "Transaction"]

CUSTOM_SEARCH_FIELDS = {
    "TransactionSearchBasic": [
        "AssemblyBuild",
        "AssemblyUnbuild",
        "BinTransfer",
        "BinWorksheet",
        "CashRefund",
        "CashSale",
        "Check",
        "CreditMemo",
        "CustomerDeposit",
        "CustomerPayment",
        "CustomerRefund",
        "CustomPurchase",
        "CustomSale",
        "Deposit",
        "DepositApplication",
        "Estimate",
        "ExpenseReport",
        "InterCompanyJournalEntry",
        "InventoryAdjustment",
        "InventoryCostRevaluation",
        "InventoryTransfer",
        "Invoice",
        "ItemFulfillment",
        "ItemReceipt",
        "JournalEntry",
        "Opportunity",
        "PaycheckJournal",
        "PurchaseOrder",
        "ReturnAuthorization",
        "SalesOrder",
        "StatisticalJournalEntry",
        "TransferOrder",
        "VendorBill",
        "VendorCredit",
        "VendorPayment",
        "VendorReturnAuthorization",
        "WorkOrder",
        "WorkOrderClose",
        "WorkOrderCompletion",
        "WorkOrderIssue",
    ],
    "ItemSearchBasic": ["InventoryItem"],
}
